version: '3.8'
services:
  frontend:
    stdin_open: true
    command: sh -c "npm i && npm start"
    depends_on:
      - api
      - db
    environment:
      - PORT=${SITE_PORT}
    image: node:latest
    restart: unless-stopped
    working_dir: "/app"
    volumes:
    - "./packages/react-frontend:/app"
    ports:
      - "${SITE_PORT}:${SITE_PORT}"
  api:
    command: sh -c "npm i && npm run dev"
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_HOST=db  
    image: node:latest
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    working_dir: "/app"
    volumes:
    - "./packages/mongo-api:/app"
  db:
    image: mongo:latest
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    volumes:
      - "./scripts/mongo:/docker-entrypoint-initdb.d/"
      - "./mock:/mock"
    ports:
      - "${DB_PORT}:${DB_PORT}"