AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template for HDVA
Metadata:
  Frontend:
    Description: Static build is deployed to public S3 Bucket

Resources:
  FrontendBucket:
    Type: 'AWS::S3::Bucket'
    DependsOn:
      - LogBucket
    Properties:
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: 
              - "*"
            AllowedMethods: 
              - "GET"
              - "POST"
            AllowedOrigins: 
              - "*"
            ExposedHeaders: 
              - "Date"
            MaxAge: '3600'
      LoggingConfiguration:
        LogFilePrefix: logs/
        DestinationBucketName: !Ref LogBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
Outputs:
  LogBucketArn:
    Value: !Ref LogBucket
  FrontendBucketArn:
    Value: !Ref FrontendBucket
    Description: S3 Bucket for object storage