name: Frontend Deployment

on: [workflow_dispatch]

jobs:
  build:
    name: Prepare Application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install and Build
      run: |
        npm ci
        npm run build
      working-directory: ./packages/react-frontend
    - name: Archive Frontend Build
      uses: actions/upload-artifact@master
      with:
        name: React Artifacts
        path: ./packages/react-frontend/build
    - name: Save AWS Settings
      uses: actions/upload-artifact@master
      with:
        name: Archive Cloudformation Settings
        path: ./.aws
  deploy:
    name: Deploy Static Site to AWS
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Setup AWS Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Download All Archives
      uses: actions/download-artifact@master
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ secrets.AWS_CLOUDFORMATION_NAME }}
        template: "Archive Cloudformation Settings/sam.template.yml"