name: Deploy Production API
on: 
  push:
    branches:
      - main
    paths:
      - "packages/sls-api/src/**"
      - "packages/sls-api/lib/**"
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: 
        go-version: '^1.13.7'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'packages/**/package-lock.json'
      name: Checkout Code and Setup Node/Go
    - run: | 
        cd ./packages/sls-api/
        npm i
        cd ./lib
        ../../../scripts/generate-packages.sh
    - name: Deploy to Production
      run: |
        cd ./packages/sls-api/
        npm run sls -- config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        npm run sls -- deploy -s production 
      env:
        JWT: ${{ secrets.JWT }}
        SLS_SERVICE: ${{ secrets.SLS_SERVICE }} 
        SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_ACCESS_KEY }}