# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: On Push to Main Branch

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Publish NPM Packages
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with: 
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@jerome-nelson'
    - name: Install Dependencies
      run: |
        npm config set //npm.pkg.github.com/:_authToken ${NPM_AUTH_TOKEN}
        npm ci
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    - name: Publish Packages
      run: npm run ci:publish