# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Get Code and Setup Git
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with: 
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@jerome-nelson'
    - name: Setup Git Identity
      uses: actions-cyborg/gha-git-credentials@v1
      with:
        name: 'Actions Cyborg'
        email: 'actions-cyborg@gmail.com'
        actor: 'actions-cyborg'
        token: '${{ secrets.GITHUB_TOKEN }}'  
    - name: Save Artifact
      uses: actions/upload-artifact@master
      with:
        name: React Artifacts
        path: .
  
  publish:
    name: Install and Publish 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@master
        with:
          name: React Artifacts
          path: .
      - name: NPM CI
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${NPM_AUTH_TOKEN}
          npm ci 
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Publish to Github Packages
        run: npm run ci:publish