name: Deploy to Test API
on: 
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Serverless Deploy
      run: |
        cd ./packages/sls-api
        npm i	
        npm run sls -- config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        npm run dev:deploy
      env:
        JWT: ${{ secrets.JWT }}
        SLS_SERVICE: ${{ secrets.SLS_SERVICE }} 
        SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_ACCESS_KEY }}